export const translations = {
  en: {
    common: {
      back: "← Back to Home"
    },
    home: {
      title: "CDPI Digital Identity",
      subtitle: "This portal demonstrates the cryptographic trust flow based on the MOSIP Inji infrastructure. Select a module to simulate a step in the lifecycle of Verifiable Credentials.",
      issuer: "The Issuer",
      holder: "The Holder",
      verifier: "The Verifier",
      certifyDesc: "CDPI Administration Interface. Generates and cryptographically signs a digital credential for a citizen.",
      walletDesc: "Mobile application simulator. Allows citizens to scan the QR Code and store their identity in a decentralized manner.",
      verifyDesc: "Access control interface. Mathematically verifies cryptographic validations without pinging the central database.",
      access: "Access"
    },
    certify: {
      title: "Inji Certify (Issuer)",
      subtitle: "CDPI Administration - Secure Credential Issuance",
      formTitle: "Citizen Identity Data",
      npi: "NPI (National Personal Identification)",
      lastName: "Last Name",
      firstName: "First Name",
      gender: "Gender",
      male: "Male",
      female: "Female",
      photoUpload: "Photo (Choose a file)",
      btnEmit: "Issue Credential (VC)",
      btnLoading: "Cryptographic Generation...",
      success: "Credential Successfully Issued!",
      successDesc: "The citizen can now scan this QR Code with their Inji Wallet.",
      devTitle: "⚙️ Developer Mode: Under the Hood",
      placeholderNpi: "Ex: 100029382",
      placeholderNom: "Ex: DUPONT",
      placeholderPrenom: "Ex: John",
      fillForm: "Fill out the form to generate the Inji credential QR Code.",
      errorMissing: "Missing Data",
      errorInternal: "Internal Server Error"
    },
    wallet: {
      title: "Inji Wallet",
      quit: "← Quit",
      empty: "No credentials",
      emptyDesc: "Scan a CDPI QR Code to add your identity.",
      myIdentities: "My Identities (Local Storage)",
      republic: "CDPI ID",
      genderAbbr: "Gender",
      share: "Share / Present",
      scanTitle: "Scan Simulation",
      scanDesc: "Paste the code generated by the Certify Issuer here.",
      btnImport: "Import Credential",
      tabs: {
        cards: "Cards",
        scan: "Scan",
        reset: "Reset"
      },
      invalidData: "This QR code is not a valid Inji credential."
    },
    verify: {
      title: "Inji Verify (Verifier)",
      subtitle: "CDPI Access Control Portal (e.g., Borders, Govt Building, Bank)",
      waitTitle: "Waiting for Credential",
      waitDesc: "Please present your digital identity via the Inji Wallet.",
      jwtLabel: "Transmitted JWT Payload (OpenID4VP Simulation)",
      btnVerify: "Check Signature (Cryptography)",
      btnLoading: "Mathematical Verification in progress...",
      authTitle: "AUTHENTIC",
      authDesc: "The document is intact and has been signed by the CDPI.",
      invalidTitle: "INVALID OR ALTERED TOKEN",
      invalidDesc: "Cryptographic signature rejected.",
      dataTitle: "Extracted certified data:",
      genderAbbr: "Gender",
      npiAbbr: "NPI",
      devTitle: "⚙️ Developer Mode: Under the Hood"
    }
  },
  fr: {
    common: {
      back: "← Retour à l'accueil"
    },
    home: {
      title: "Identité Numérique CDPI",
      subtitle: "Ce portail démontre le flux de confiance cryptographique basé sur l'infrastructure MOSIP Inji. Sélectionnez un module pour simuler une étape du cycle de vie des Attestations Vérifiables.",
      issuer: "L'Émetteur",
      holder: "Le Détenteur",
      verifier: "Le Vérificateur",
      certifyDesc: "Interface d'administration CDPI. Permet de générer et de signer cryptographiquement une attestation numérique pour un citoyen.",
      walletDesc: "Simulateur de l'application mobile. Permet au citoyen de scanner le QR Code et de stocker son identité de façon décentralisée.",
      verifyDesc: "Interface de contrôle des accès. Vérifie mathématiquement les validations cryptographiques sans ping à la base centrale.",
      access: "Accéder"
    },
    certify: {
      title: "Inji Certify (Émetteur)",
      subtitle: "Administration CDPI - Émission d'Attestations Sécurisées",
      formTitle: "Données d'Identité du Citoyen",
      npi: "NPI (Numéro Personnel d'Identification)",
      lastName: "Nom",
      firstName: "Prénom",
      gender: "Genre",
      male: "Masculin",
      female: "Féminin",
      photoUpload: "Photo (Choisir un fichier)",
      btnEmit: "Émettre l'Attestation (VC)",
      btnLoading: "Génération Cryptographique...",
      success: "Attestation Émise avec Succès !",
      successDesc: "Le citoyen peut maintenant scanner ce QR Code avec son Inji Wallet.",
      devTitle: "⚙️ Mode Développeur : Sous Le Capot",
      placeholderNpi: "Ex: 100029382",
      placeholderNom: "Ex: DUPONT",
      placeholderPrenom: "Ex: Jean",
      fillForm: "Remplissez le formulaire pour générer le QR Code de l'attestation Inji.",
      errorMissing: "Données manquantes",
      errorInternal: "Erreur interne du serveur"
    },
    wallet: {
      title: "Inji Wallet",
      quit: "← Quitter",
      empty: "Aucune attestation",
      emptyDesc: "Scannez un QR Code CDPI pour ajouter votre identité.",
      myIdentities: "Mes Identités (Stockage Local)",
      republic: "ID CDPI",
      genderAbbr: "Sexe",
      share: "Partager / Présenter",
      scanTitle: "Simulation de Scan",
      scanDesc: "Collez le code généré par l'Émetteur Certify ici.",
      btnImport: "Importer l'Attestation",
      tabs: {
        cards: "Cartes",
        scan: "Scanner",
        reset: "Reset"
      },
      invalidData: "Ce QR code n'est pas une attestation Inji valide."
    },
    verify: {
      title: "Inji Verify (Vérificateur)",
      subtitle: "Portail de contrôle d'accès CDPI (Ex: Frontières, Bâtiment Gouvernemental, Banque)",
      waitTitle: "Attente de l'Attestation",
      waitDesc: "Veuillez présenter votre identité numérique via l'Inji Wallet.",
      jwtLabel: "Payload JWT Transmis (Simulation OpenID4VP)",
      btnVerify: "Contrôler la Signature (Cryptographie)",
      btnLoading: "Vérification Mathématique en cours...",
      authTitle: "AUTHENTIQUE",
      authDesc: "Le document est intègre et a bien été signé par le CDPI.",
      invalidTitle: "JETON INVALIDE OU ALTÉRÉ",
      invalidDesc: "Signature cryptographique rejetée.",
      dataTitle: "Données certifiées extraites :",
      genderAbbr: "Sexe",
      npiAbbr: "NPI",
      devTitle: "⚙️ Mode Développeur : Sous Le Capot"
    }
  }
};
